# Generated by Django 4.2.3 on 2023-08-13 21:44

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('image', models.ImageField(upload_to='external_sites')),
                ('url', models.URLField()),
                ('order', models.SmallIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='projects')),
                ('text', ckeditor.fields.RichTextField()),
                ('order', models.SmallIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
