# Generated by Django 4.2.22 on 2025-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='hi-bye'),
            preserve_default=False,
        ),
    ]
