# Generated by Django 4.2.3 on 2023-09-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['owner', 'title']},
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='name',
            new_name='title',
        ),
    ]
