# Generated by Django 4.2.22 on 2025-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_text',
            field=models.TextField(default='INSERT'),
            preserve_default=False,
        ),
    ]
