# Generated by Django 4.2.22 on 2025-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsite',
            name='image_text',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
