# Generated by Django 4.2.22 on 2025-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_externalsite_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='cover_images'),
        ),
    ]
