# Generated by Django 4.2.22 on 2025-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
