# Generated by Django 4.2.22 on 2025-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_text',
            field=models.TextField(default='Hi'),
            preserve_default=False,
        ),
    ]
