# Generated by Django 4.2.22 on 2025-08-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tab',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
