# Generated by Django 4.2.22 on 2025-08-20 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_tab_options_tab_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsite',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['https', 'mailto'])]),
        ),
    ]
