# Generated by Django 4.2.22 on 2025-08-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_externalsite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsite',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
